### ISSUE TITLE
More on conformers

### ISSUE THREAD

**Issue by hansen7** [learningmatter-mit/geom#4]
Thanks for the sharing, I just realise how well the organisation is! (especially for the conformers)

I have a few more questions.

1. The Language-agnostic and Python-specific data represent the **same** pieces of information (i.e., molecules and their corresponding conformers). I mean besides the updated content in RDKit, right?

The following questions are specifically on conformers.

<img width="763" alt="image" src="https://user-images.githubusercontent.com/14752739/120131174-bf759300-c1bf-11eb-8abd-b83b87c1bc6d.png">

2. Does this always hold? 
`totalconfs` - `uniqueconfs` (i.e., len(that_mole_dict[''conformers')) == # of rotamers 

3. How to get the rotamers?  Since you've provided the fine-grained 'conformerweights' (i.e., a list).

4. I am not sure about the physical meaning of `set`, would you mind elaborating it a bit more?

5. if a molecule is included in more than one datasets, are its attribute values consistent across these datasets?

6. How can we automatically discover/remove conformers as `example 1` shown in the `02_loading_rdkit_mols.ipynb`? Since they are essentially not aligned with the general concept of conformer.

7. `example 2` seems to be another (issue) from the simulation? Any update thoughts on it?

**Comment by simonaxelrod** [comment]
Thanks @hansen7! Glad you're enjoying it.

1. They do **not** represent the same data. We have not updated the messagepack files with new SARS-CoV-2 data. We also won't do so for any new data that we add. This is because the pickle files are much easier to handle. 
2. If you define "# of rotamers" as the number of _extra_ structures that are chemically equivalent to the conformers given, then yes.
3. Unfortunately the rotamers are not provided in the dataset.
4. `set` is a quantity produced by CREST calculations. I believe it refers to the index of the MD simulations that the conformer came from. 12 different metadynamics parameters are used to produce 12 independent sets of trajectories, and I believe `set` refers to one of these 12 indices.
5. Can you explain what you mean by attributed values?
6. You can check that all conformers have the same graph by using RDKit to convert the Mol objects to canonical SMILES strings:
```python
from rdkit import Chem

# get their SMILES strings
conf_list = [Chem.MolToSmiles(Chem.MolFromSmiles(Chem.MolToSmiles(rd_mol))) for rdmol in conf_rdmols]
# check that they're all the same
same_confs = len(list(set(conf_list))) == 1
```
You could alternatively compare the inchi keys:
```python
from rdkit import Chem

# get their inchi keys
conf_list = [Chem.MolToInchikey(rd_mol) for rdmol in conf_rdmols]
# check that they're all the same
same_confs = len(list(set(conf_list))) == 1
```
I think this should actually address the issue in `example 2`, because in my experience inchi is able to identify to resonance structures as equivalent. But it's worth checking to see if it works.

7. See 6.

Hope this helps!

**Comment by hansen7** [comment]
Thanks for the elaboration! I have a  few follow-ups questions:

> 2. If you define "# of rotamers" as the number of _extra_ structures that are chemically equivalent to the conformers given, then yes.
> 3. Unfortunately the rotamers are not provided in the dataset.

I see, is there a way we can derive all the rotamers on our own?

> 5. Can you explain what you mean by attributed values?

Oh, I mean physical properties like `total energy`, `ensemble energy`, `ensemble entropy` in the screenshot. Just from the sanity check perspective, I am wondering if these physical properties are consistent (identical) across different datasets.

**Comment by simonaxelrod** [comment]
3. Sadly I don't know of a simple way to do that :( 
5. By different datasets do you mean different experimental datasets? If so, then yes. Each species is only in GEOM once, even if it is present in different experimental datasets. This means that it only has one set of CREST values (total energy, ensemble energy, etc.). If it has multiple experimental properties (e.g. active against SARS CoV and active against SARS-CoV-2), then these will be included in the `sample_dic[sample_smiles]` dictionary.

For example, in the screenshot, both the `sars_cov_one_pl_protease` and `sars_cov_one_cl_protease_active` properies are present. These come from two different experimental datasets, which we can see through `saample_dic[sample_smiles][datasets] = [aid1706, plpro]`.

**Comment by hansen7** [comment]
Thanks! I don't have further questions by far!
