### ISSUE TITLE
Need preprocessing codes for molecules given as clusters

### ISSUE THREAD

**Issue by Qcactus** [learningmatter-mit/geom#8]
Hi, thanks for this awesome dataset!

Can you make the preprocessing codes for SMILES public？There seems to be some special processing for SMILES of molecules with counterbalancing ions or acids. I may need these codes to process downstream datasets.

**Comment by simonaxelrod** [comment]
Hey @Qcactus - our pleasure! The code actually involves a lot of functions from the in-house repo that interfaces with our database. The repo is gigantic, so it wouldn't be straightforward to make the code public. If you end up needing the preprocessing code, send me a message and I can help you with that process.

**Comment by Qcactus** [comment]
@simonaxelrod Hi, I've sent an email about this issue to simonaxelrod@g.harvard.edu a few days ago, but haven't heard from you since then. I'm not sure if it is your current mailbox.

I need to process some salt-like and acid-base molecules in the same way as GEOM dataset. Could you please provide these codes, or just show me some key steps like what functions in RDKit and what reaction SMARTS are used?

**Comment by simonaxelrod** [comment]
@Qcactus sorry about that! I got the email but hadn't gotten around to cleaning up the code yet. I'll email it to you in the next couple hours

**Comment by simonaxelrod** [comment]
Apologies for the delay -- here is a zip file of the code we used for
molecule processing. The conda environment we used when running the code
can be created from "environment.yml". We used a number of functions from
our database repository to create the reactions, and I've copied the
relevant folders into this one. They are "blocks", "confgen", and "molgen".
They're quite big and complicated, but basically their use is to create
reactions from smarts strings and then use the product molecules for
something downstream.

The actual code we used to create the reactions is given in the jupyter
notebook, Reactions_Covid_ionization.ipynb. It will be a little bit
confusing for you, since it involves references to Django classes that
we've created for our database: "Species", "Reaction", "Mol", "Group", and
so on. I would try to ignore these Django references and instead try to
focus on the general logic of the reactions.

Lastly, please do not distribute this code, as we haven't yet open sourced
our database repository yet.

Happy coding!

Simon

**Comment by Qcactus** [comment]
@simonaxelrod Thanks for your response! I receiced your email, but there is no code file attached. How can I get the file?

**Comment by simonaxelrod** [comment]
Just sent it again - let me know if you got it this time

**Comment by Qcactus** [comment]
Yes, I got the codes. Thank you very much!

**Comment by simonaxelrod** [comment]
No problem!
