### ISSUE TITLE
xyz data for lipo dataset

### ISSUE THREAD

**Issue by heliogabale** [learningmatter-mit/geom#9]
Hello,
Thanks for putting these data and those well structured companion notebooks.
 In the lipo datasets I cannot find the xyz data. 
To retrieve them I used the code in the notebook

lipo_dic = {key: val for key, val in summary.items() if 'lipo' in val.get('datasets', [])}
overall_dict = {}

for key in tqdm(lipo_dic.keys()):
    val = lipo_dic[key]
    pickle_path = os.path.join(molecule_net_path, val['pickle_path'])
    with open(pickle_path, 'rb') as f:
        conf_dic = pickle.load(f)
    overall_dict[key] = conf_dic

key_iter=list(overall_dict.keys())
I was looking bu iterating over the key_iter
overall_dict[key_iter[1]]['conformers']
Thanks for your help

**Comment by simonaxelrod** [comment]
Hey @heliogabale - thanks for the kind words, and I'm happy that you're enjoying the dataset! When you say that you can't find the xyz data, do you mean that `lipo_dic` is empty? Or that it is full, but the information that populates it doesn't have any xyz information?

If it's the first issue, then I ran the code you gave and found 4,194 items in `lipo_dic` and `overall_dict`. If it's the second issue, then you may not see the xyz data, because it's actually contained in `rd_mol`. Try this code to get the xyz data from the RDKit mols:

```python
import numpy as np

rd_mol = overall_dict[key_iter[1]]['conformers'][0]['rd_mol']
coords = rd_mol.GetConformers()[0].GetPositions()
atomic_numbers = np.array([atom.GetAtomicNum() for atom in rd_mol.GetAtoms()])

print(atomic_numbers, coords)
```

Does this help?

**Comment by heliogabale** [comment]
This solves my problem. Thanks a lot

**Comment by simonaxelrod** [comment]
Great!
